# Generated by Django 4.1.2 on 2022-11-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0006_alter_contato_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='Pessoal', max_length=256),
        ),
    ]
