# Generated by Django 4.1.2 on 2022-11-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0007_alter_contato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='Contato próprio', max_length=256),
        ),
    ]
